# Dados históricos das Olimpíadas (1896-2016)

Jogos Olímpicos são um evento multiesportivo global com modalidades de verão e de inverno, em que milhares de atletas participam de várias competições. Atualmente os Jogos são realizados a cada dois anos, em anos pares, com os Jogos Olímpicos de Verão e de Inverno se alternando, embora ocorram a cada quatro anos no âmbito dos respectivos Jogos sazonais. Originalmente, os Jogos Olímpicos da Antiguidade foram realizados em Olímpia, na Grécia, do século VIII a.C. ao século V d.C.. No século XIX, o Barão Pierre de Coubertin fundou o Comitê Olímpico Internacional (COI) em 1894. O COI se tornou o órgão dirigente do Movimento Olímpico, cuja estrutura e as ações são definidas pela Carta Olímpica.

Os Jogos Olímpicos antigos foram uma série de competições realizadas entre representantes de várias cidades-estado da Grécia antiga, que caracterizou principalmente eventos atléticos, mas também de combate e corridas de bigas. A origem destes Jogos Olímpicos é envolta em mistério e lendas. Um dos mitos mais populares identifica Hércules e Zeus, seu pai, como os progenitores dos Jogos.

In [1]:
!pip install basedosdados

Requirement already satisfied: basedosdados in c:\users\luiz gustavo\anaconda3\lib\site-packages (1.6.8)
Requirement already satisfied: ckanapi==4.6 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (4.6)
Requirement already satisfied: pandas-gbq<0.18.0,>=0.17.4 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (0.17.9)
Requirement already satisfied: mkdocstrings<0.19.0,>=0.18.1 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (0.18.1)
Requirement already satisfied: tomlkit==0.7.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (0.7.0)
Requirement already satisfied: tqdm==4.50.2 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (4.50.2)
Requirement already satisfied: Jinja2==3.0.3 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (3.0.3)
Requirement already satisfied: importlib-metadata<5.0.0,>=4.11.3 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (4.11.3)
Requirement already satisfied: pyaml==20.4.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (20.4.0)
Requirement already satisfied: ruamel.yaml==0.17.10 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (0.17.10)
Requirement already satisfied: click==8.0.3 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (8.0.3)
Requirement already satisfied: pandavro<2.0.0,>=1.6.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (1.7.1)
Requirement already satisfied: loguru<0.7.0,>=0.6.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (0.6.0)
Requirement already satisfied: mkdocs-click<0.6.0,>=0.5.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (0.5.0)
Requirement already satisfied: mkdocs<2.0.0,>=1.2.3 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (1.4.0)
Requirement already satisfied: pytest==6.0.2 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (6.0.2)
Requirement already satisfied: mkdocs-material<9.0.0,>=8.2.7 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (8.5.6)
Requirement already satisfied: ipykernel==5.3.4 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (5.3.4)
Requirement already satisfied: black==20.8b1 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (20.8b1)
Requirement already satisfied: jupyter<2.0.0,>=1.0.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (1.0.0)
Requirement already satisfied: google-cloud-bigquery-storage==1.1.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (1.1.0)
Requirement already satisfied: google-cloud-bigquery==2.30.1 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (2.30.1)
Requirement already satisfied: google-cloud-storage==1.42.3 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (1.42.3)
Requirement already satisfied: pyarrow==6.0.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (6.0.0)
Requirement already satisfied: pandas==1.2.4 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (1.2.4)
Requirement already satisfied: toml<0.11.0,>=0.10.2 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from basedosdados) (0.10.2)
Requirement already satisfied: appdirs in c:\users\luiz gustavo\anaconda3\lib\site-packages (from black==20.8b1->basedosdados) (1.4.4)
Requirement already satisfied: typing-extensions>=3.7.4 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from black==20.8b1->basedosdados) (4.1.1)
Requirement already satisfied: regex>=2020.1.8 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from black==20.8b1->basedosdados) (2022.3.15)
Requirement already satisfied: pathspec<1,>=0.6 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from black==20.8b1->basedosdados) (0.7.0)
Requirement already satisfied: typed-ast>=1.4.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from black==20.8b1->basedosdados) (1.4.3)
Requirement already satisfied: mypy-extensions>=0.4.3 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from black==20.8b1->basedosdados) (0.4.3)
Requirement already satisfied: requests in c:\users\luiz gustavo\anaconda3\lib\site-packages (from ckanapi==4.6->basedosdados) (2.27.1)
Requirement already satisfied: docopt in c:\users\luiz gustavo\anaconda3\lib\site-packages (from ckanapi==4.6->basedosdados) (0.6.2)
Requirement already satisfied: six<2.0,>=1.9 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from ckanapi==4.6->basedosdados) (1.16.0)
Requirement already satisfied: setuptools in c:\users\luiz gustavo\anaconda3\lib\site-packages (from ckanapi==4.6->basedosdados) (61.2.0)
Requirement already satisfied: python-slugify>=1.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from ckanapi==4.6->basedosdados) (5.0.2)
Requirement already satisfied: colorama in c:\users\luiz gustavo\anaconda3\lib\site-packages (from click==8.0.3->basedosdados) (0.4.4)
Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from google-cloud-bigquery==2.30.1->basedosdados) (1.3.1)
Requirement already satisfied: protobuf>=3.12.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from google-cloud-bigquery==2.30.1->basedosdados) (3.20.3)
Requirement already satisfied: proto-plus>=1.10.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from google-cloud-bigquery==2.30.1->basedosdados) (1.22.1)
Requirement already satisfied: grpcio<2.0dev,>=1.38.1 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from google-cloud-bigquery==2.30.1->basedosdados) (1.49.1)
Requirement already satisfied: google-api-core[grpc]<3.0.0dev,>=1.29.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from google-cloud-bigquery==2.30.1->basedosdados) (1.33.2)
Requirement already satisfied: google-cloud-core<3.0.0dev,>=1.4.1 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from google-cloud-bigquery==2.30.1->basedosdados) (1.7.1)
Requirement already satisfied: packaging>=14.3 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from google-cloud-bigquery==2.30.1->basedosdados) (21.3)
Requirement already satisfied: python-dateutil<3.0dev,>=2.7.2 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from google-cloud-bigquery==2.30.1->basedosdados) (2.8.2)
Requirement already satisfied: google-auth<3.0dev,>=1.25.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from google-cloud-storage==1.42.3->basedosdados) (1.33.0)
Requirement already satisfied: jupyter-client in c:\users\luiz gustavo\anaconda3\lib\site-packages (from ipykernel==5.3.4->basedosdados) (6.1.12)
Requirement already satisfied: tornado>=4.2 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from ipykernel==5.3.4->basedosdados) (6.1)
Requirement already satisfied: traitlets>=4.1.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from ipykernel==5.3.4->basedosdados) (5.1.1)
Requirement already satisfied: ipython>=5.0.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from ipykernel==5.3.4->basedosdados) (8.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from Jinja2==3.0.3->basedosdados) (2.0.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from pandas==1.2.4->basedosdados) (2021.3)
Requirement already satisfied: numpy>=1.16.5 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from pandas==1.2.4->basedosdados) (1.21.5)
Requirement already satisfied: PyYAML in c:\users\luiz gustavo\anaconda3\lib\site-packages (from pyaml==20.4.0->basedosdados) (6.0)
Requirement already satisfied: pluggy<1.0,>=0.12 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from pytest==6.0.2->basedosdados) (0.13.1)
Requirement already satisfied: attrs>=17.4.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from pytest==6.0.2->basedosdados) (21.4.0)
Requirement already satisfied: py>=1.8.2 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from pytest==6.0.2->basedosdados) (1.11.0)
Requirement already satisfied: iniconfig in c:\users\luiz gustavo\anaconda3\lib\site-packages (from pytest==6.0.2->basedosdados) (1.1.1)
Requirement already satisfied: atomicwrites>=1.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from pytest==6.0.2->basedosdados) (1.4.0)
Requirement already satisfied: more-itertools>=4.0.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from pytest==6.0.2->basedosdados) (8.14.0)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from ruamel.yaml==0.17.10->basedosdados) (0.2.6)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.56.2 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from google-api-core[grpc]<3.0.0dev,>=1.29.0->google-cloud-bigquery==2.30.1->basedosdados) (1.56.4)
Requirement already satisfied: grpcio-status<2.0dev,>=1.33.2 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from google-api-core[grpc]<3.0.0dev,>=1.29.0->google-cloud-bigquery==2.30.1->basedosdados) (1.48.2)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage==1.42.3->basedosdados) (4.7.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage==1.42.3->basedosdados) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage==1.42.3->basedosdados) (4.2.2)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery==2.30.1->basedosdados) (1.1.2)
Requirement already satisfied: cffi>=1.0.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from google-crc32c<2.0dev,>=1.0->google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery==2.30.1->basedosdados) (1.15.0)
Requirement already satisfied: pycparser in c:\users\luiz gustavo\anaconda3\lib\site-packages (from cffi>=1.0.0->google-crc32c<2.0dev,>=1.0->google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery==2.30.1->basedosdados) (2.21)
Requirement already satisfied: zipp>=0.5 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from importlib-metadata<5.0.0,>=4.11.3->basedosdados) (3.7.0)
Requirement already satisfied: jedi>=0.16 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel==5.3.4->basedosdados) (0.18.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel==5.3.4->basedosdados) (3.0.20)
Requirement already satisfied: pygments>=2.4.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel==5.3.4->basedosdados) (2.13.0)
Requirement already satisfied: backcall in c:\users\luiz gustavo\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel==5.3.4->basedosdados) (0.2.0)
Requirement already satisfied: pickleshare in c:\users\luiz gustavo\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel==5.3.4->basedosdados) (0.7.5)
Requirement already satisfied: stack-data in c:\users\luiz gustavo\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel==5.3.4->basedosdados) (0.2.0)
Requirement already satisfied: matplotlib-inline in c:\users\luiz gustavo\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel==5.3.4->basedosdados) (0.1.2)
Requirement already satisfied: decorator in c:\users\luiz gustavo\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel==5.3.4->basedosdados) (5.1.1)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=5.0.0->ipykernel==5.3.4->basedosdados) (0.8.3)
Requirement already satisfied: qtconsole in c:\users\luiz gustavo\anaconda3\lib\site-packages (from jupyter<2.0.0,>=1.0.0->basedosdados) (5.3.0)
Requirement already satisfied: notebook in c:\users\luiz gustavo\anaconda3\lib\site-packages (from jupyter<2.0.0,>=1.0.0->basedosdados) (6.4.8)
Requirement already satisfied: ipywidgets in c:\users\luiz gustavo\anaconda3\lib\site-packages (from jupyter<2.0.0,>=1.0.0->basedosdados) (7.6.5)
Requirement already satisfied: nbconvert in c:\users\luiz gustavo\anaconda3\lib\site-packages (from jupyter<2.0.0,>=1.0.0->basedosdados) (6.4.4)
Requirement already satisfied: jupyter-console in c:\users\luiz gustavo\anaconda3\lib\site-packages (from jupyter<2.0.0,>=1.0.0->basedosdados) (6.4.0)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from loguru<0.7.0,>=0.6.0->basedosdados) (1.1.0)
Requirement already satisfied: mergedeep>=1.3.4 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from mkdocs<2.0.0,>=1.2.3->basedosdados) (1.3.4)
Requirement already satisfied: watchdog>=2.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from mkdocs<2.0.0,>=1.2.3->basedosdados) (2.1.6)
Requirement already satisfied: Markdown<3.4,>=3.2.1 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from mkdocs<2.0.0,>=1.2.3->basedosdados) (3.3.4)
Requirement already satisfied: pyyaml-env-tag>=0.1 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from mkdocs<2.0.0,>=1.2.3->basedosdados) (0.1)
Requirement already satisfied: ghp-import>=1.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from mkdocs<2.0.0,>=1.2.3->basedosdados) (2.1.0)
Requirement already satisfied: mkdocs-material-extensions>=1.0.3 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from mkdocs-material<9.0.0,>=8.2.7->basedosdados) (1.0.3)
Requirement already satisfied: pymdown-extensions>=9.4 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from mkdocs-material<9.0.0,>=8.2.7->basedosdados) (9.6)
Requirement already satisfied: mkdocs-autorefs>=0.3.1 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from mkdocstrings<0.19.0,>=0.18.1->basedosdados) (0.4.1)
Requirement already satisfied: mkdocstrings-python-legacy>=0.2 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from mkdocstrings<0.19.0,>=0.18.1->basedosdados) (0.2.2)
Requirement already satisfied: pytkdocs>=0.14 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from mkdocstrings-python-legacy>=0.2->mkdocstrings<0.19.0,>=0.18.1->basedosdados) (0.16.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from packaging>=14.3->google-cloud-bigquery==2.30.1->basedosdados) (3.0.4)
Requirement already satisfied: google-auth-oauthlib>=0.0.1 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from pandas-gbq<0.18.0,>=0.17.4->basedosdados) (0.5.3)
Requirement already satisfied: pydata-google-auth in c:\users\luiz gustavo\anaconda3\lib\site-packages (from pandas-gbq<0.18.0,>=0.17.4->basedosdados) (1.4.0)
Requirement already satisfied: db-dtypes<2.0.0,>=0.3.1 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from pandas-gbq<0.18.0,>=0.17.4->basedosdados) (1.0.4)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from google-auth-oauthlib>=0.0.1->pandas-gbq<0.18.0,>=0.17.4->basedosdados) (1.3.1)
Requirement already satisfied: fastavro==1.5.1 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from pandavro<2.0.0,>=1.6.0->basedosdados) (1.5.1)
Requirement already satisfied: wcwidth in c:\users\luiz gustavo\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.0.0->ipykernel==5.3.4->basedosdados) (0.2.5)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0dev,>=1.25.0->google-cloud-storage==1.42.3->basedosdados) (0.4.8)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from python-slugify>=1.0->ckanapi==4.6->basedosdados) (1.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from requests->ckanapi==4.6->basedosdados) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from requests->ckanapi==4.6->basedosdados) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from requests->ckanapi==4.6->basedosdados) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from requests->ckanapi==4.6->basedosdados) (1.26.9)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.0.1->pandas-gbq<0.18.0,>=0.17.4->basedosdados) (3.2.1)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from ipywidgets->jupyter<2.0.0,>=1.0.0->basedosdados) (5.3.0)
Requirement already satisfied: ipython-genutils~=0.2.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from ipywidgets->jupyter<2.0.0,>=1.0.0->basedosdados) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.5.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from ipywidgets->jupyter<2.0.0,>=1.0.0->basedosdados) (3.5.2)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from ipywidgets->jupyter<2.0.0,>=1.0.0->basedosdados) (1.0.0)
Requirement already satisfied: jsonschema>=2.6 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets->jupyter<2.0.0,>=1.0.0->basedosdados) (4.4.0)
Requirement already satisfied: jupyter-core in c:\users\luiz gustavo\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets->jupyter<2.0.0,>=1.0.0->basedosdados) (4.9.2)
Requirement already satisfied: fastjsonschema in c:\users\luiz gustavo\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets->jupyter<2.0.0,>=1.0.0->basedosdados) (2.15.1)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets->jupyter<2.0.0,>=1.0.0->basedosdados) (0.18.0)
Requirement already satisfied: argon2-cffi in c:\users\luiz gustavo\anaconda3\lib\site-packages (from notebook->jupyter<2.0.0,>=1.0.0->basedosdados) (21.3.0)
Requirement already satisfied: prometheus-client in c:\users\luiz gustavo\anaconda3\lib\site-packages (from notebook->jupyter<2.0.0,>=1.0.0->basedosdados) (0.13.1)
Requirement already satisfied: Send2Trash>=1.8.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from notebook->jupyter<2.0.0,>=1.0.0->basedosdados) (1.8.0)
Requirement already satisfied: pyzmq>=17 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from notebook->jupyter<2.0.0,>=1.0.0->basedosdados) (22.3.0)
Requirement already satisfied: nest-asyncio>=1.5 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from notebook->jupyter<2.0.0,>=1.0.0->basedosdados) (1.5.5)
Requirement already satisfied: terminado>=0.8.3 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from notebook->jupyter<2.0.0,>=1.0.0->basedosdados) (0.13.1)
Requirement already satisfied: pywin32>=1.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from jupyter-core->nbformat>=4.2.0->ipywidgets->jupyter<2.0.0,>=1.0.0->basedosdados) (302)
Requirement already satisfied: pywinpty>=1.1.0 in c:\users\luiz gustavo\anaconda3\lib\site-packages (from terminado>=0.8.3->notebook->jupyter<2.0.0,>=1.0.0->basedosdados) (2.0.2)

In [2]:
import basedosdados as bd

# Para carregar o dado direto no pandas
df = bd.read_table(dataset_id='mundo_kaggle_olimpiadas',
table_id='microdados',
billing_project_id="api-365415")

Downloading: 100%|█████████████████████████████████████████████████████████| 269718/269718 [00:49<00:00, 5416.92rows/s]

A tabela a ser apresentada consiste nos dados dos atletas registrados nas edições das olimpíadas desde 1896 até 2016. 
Nas linhas são descritas informações de cada atleta, sendo elas: delegação, equipe, id, nome, sexo, idade, altura, peso, esporte, evento e medalha. Também são descritas informações da edição da olímpiada em que o atleta participou, sendo elas: ano, edição, cidade sede e país.

Essa é uma amostra da tabela completa:

In [4]:
df

,ano,edicao,cidade_sede,pais,delegacao,equipe,id_atleta,nome_atleta,sexo,idade,altura,peso,esporte,evento,medalha
0,1896,Summer,Athina,Australia,AUS,Australia,35698,"Edwin Harold ""Teddy"" Flack",M,22,<NA>,<NA>,Athletics,"Athletics Men's 1,500 metres",Gold
1,1896,Summer,Athina,Australia,AUS,Australia,35698,"Edwin Harold ""Teddy"" Flack",M,22,<NA>,<NA>,Athletics,Athletics Men's 800 metres,Gold
2,1896,Summer,Athina,Australia,AUS,Australia,35698,"Edwin Harold ""Teddy"" Flack",M,22,<NA>,<NA>,Athletics,Athletics Men's Marathon,None
3,1896,Summer,Athina,Australia,AUS,Australia/Great Britain,35698,"Edwin Harold ""Teddy"" Flack",M,22,<NA>,<NA>,Tennis,Tennis Men's Doubles,Bronze
4,1896,Summer,Athina,Australia,AUS,Australia,35698,"Edwin Harold ""Teddy"" Flack",M,22,<NA>,<NA>,Tennis,Tennis Men's Singles,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269713,2016,Summer,Rio de Janeiro,None,SGP,Singapore,133071,"Pei Lin ""Audrey"" Yong",F,21,156,50,Sailing,Sailing Women's Windsurfer,None
269714,2016,Summer,Rio de Janeiro,None,SGP,Singapore,133346,Yu Mengyu,F,26,166,50,Table Tennis,Table Tennis Women's Singles,None
269715,2016,Summer,Rio de Janeiro,None,SGP,Singapore,133346,Yu Mengyu,F,26,166,50,Table Tennis,Table Tennis Women's Team,None
269716,2016,Summer,Rio de Janeiro,None,SGP,Singapore,134826,Zhou Yihan,F,22,168,54,Table Tennis,Table Tennis Women's Team,None
269717,2016,Summer,Rio de Janeiro,None,TUV,Tuvalu,120422,Etimoni Timuani,M,24,184,72,Athletics,Athletics Men's 100 metres,None

Essas são os tipos de variáveis das colunas:

In [5]:
df.dtypes

ano             Int64
edicao         object
cidade_sede    object
pais           object
delegacao      object
equipe         object
id_atleta      object
nome_atleta    object
sexo           object
idade           Int64
altura          Int64
peso            Int64
esporte        object
evento         object
medalha        object
dtype: object

Essa é a quantidade de atletas inscritos em todas as olimpíadas:

In [6]:
df['nome_atleta'].count()

269718

Aqui é possível buscar pelo nome de um atleta olímpico, também é possível colocar o ano da edição da olímpiada para que a busca possa ser mais apurada:

In [4]:
import pandas as pd
 
resposta = input('Deseja buscar um nome? (s/n): ')
while resposta == 's':
    nome = input('Digite o nome ou o sobrenome do atleta olímpico: ')
    ano = input('Digite o ano da olimpíada:')
    df['ano'] = df['ano'].map(str)
    df_nome = df[df['nome_atleta'].str.contains(nome, na = False)]
    df_resultado = df_nome[df_nome['ano'].str.contains(ano, na = False)]
    display(df_resultado)
    baixar = input('Deseja baixar o resultado no formato XLSX? (s/n): ')
    if baixar == 's':
        nomeArquivo = input('Digite o nome que quer dar ao arquivo: ')
        df_resultado.to_excel(f'{nomeArquivo}.xlsx')
    resposta = input('Deseja continuar buscando? (s/n): ')
    
print('Fim do programa.')

Deseja buscar um nome? (s/n): s
Digite o nome ou o sobrenome do atleta olímpico: Mario
Digite o ano da olimpíada:2012

,ano,edicao,cidade_sede,pais,delegacao,equipe,id_atleta,nome_atleta,sexo,idade,altura,peso,esporte,evento,medalha
238351,2012,Summer,London,Argentina,ARG,Argentina,19283,Mario Cejas,M,34,181,75,Rowing,Rowing Men's Lightweight Double Sculls,None
238953,2012,Summer,London,Australia,AUS,Australia,115554,Belinda Josephine Marion Stowell,F,41,172,68,Sailing,Sailing Women's Two Person Dinghy,None
241002,2012,Summer,London,Colombia,COL,Colombia,30773,Mariana Duque Mario,F,22,169,61,Tennis,Tennis Women's Singles,None
241051,2012,Summer,London,Colombia,COL,Colombia,89318,Carlos Mario Oquendo Zabala,M,24,186,85,Cycling,Cycling Men's BMX,Bronze
241109,2012,Summer,London,Costa Rica,CRC,Costa Rica,81584,Mario Enrique Montoya Segnini,M,22,195,96,Swimming,Swimming Men's 200 metres Freestyle,None
241218,2012,Summer,London,Croatia,CRO,Croatia,120699,Mario Todorovi,M,23,186,80,Swimming,Swimming Men's 50 metres Freestyle,None
241222,2012,Summer,London,Croatia,CRO,Croatia,125697,Mario Veki,M,29,190,94,Rowing,Rowing Men's Single Sculls,None
241355,2012,Summer,London,Cyprus,CYP,Cyprus,5792,Marios Athanasiadis,M,25,179,70,Cycling,"Cycling Men's Mountainbike, Cross-Country",None
242206,2012,Summer,London,France,FRA,France,34072,Marion Farissier,F,20,164,64,Diving,Diving Women's Springboard,None
242287,2012,Summer,London,France,FRA,France,65669,Marion Laborde,F,25,178,75,Basketball,Basketball Women's Basketball,Silver
242326,2012,Summer,London,France,FRA,France,71622,Marion Lotout,F,22,165,50,Athletics,Athletics Women's Pole Vault,None
243250,2012,Summer,London,Honduras,HON,Honduras,75808,Mario Roberto Martnez Hernndez,M,22,170,70,Football,Football Men's Football,None
243926,2012,Summer,London,Italy,ITA,Italy,28086,Tania Di Mario,F,33,168,62,Water Polo,Water Polo Women's Water Polo,None
244081,2012,Summer,London,Italy,ITA,Italy,91176,Mario Paonessa,M,21,190,85,Rowing,Rowing Men's Coxless Fours,None
246132,2012,Summer,London,Peru,PER,Peru,8950,Mario Alfonzo Bazn Argandoa,M,24,175,64,Athletics,"Athletics Men's 3,000 metres Steeplechase",None
248231,2012,Summer,London,Spain,ESP,Spain,38650,Mario Jos Garca Rodrguez,M,29,190,91,Water Polo,Water Polo Men's Water Polo,None
248334,2012,Summer,London,Spain,ESP,Spain,81075,Mario Mola Daz,M,22,178,63,Triathlon,Triathlon Men's Olympic Distance,None
248370,2012,Summer,London,Spain,ESP,Spain,93755,Mario Pestano Garca,M,34,195,120,Athletics,Athletics Men's Discus Throw,None
248675,2012,Summer,London,Switzerland,SUI,Switzerland,44384,Mario-Elio Gyr,M,27,187,76,Rowing,Rowing Men's Lightweight Coxless Fours,None

Deseja baixar o resultado no formato XLSX? (s/n): n
Deseja continuar buscando? (s/n): n
Fim do programa.